version: "3.8"

services:
  discovery:
    build: .
    container_name: voting-system-discovery
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761
    networks:
      - app-net

networks:
  app-net:
    external: true
